name: Leafy Branches
favicon: null
layout_spectrum: 0.25928
typography_spectrum: 0.302105369977653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c80113'
    - '#fd9c00'
    - '#007700'
    - '#fafff7'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
