name: Leafy Branches
favicon: null
layout_spectrum: 0.25928
typography_spectrum: 0.302105369977653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3a3a3a'
    - '#eaeaea'
    - '#797979'
    - '#a6a6a6'
    - '#29828a'
  brandStrength: 0.625
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
